#!/bin/sh
#
# antlr3 script, based on example antlr3 commandline
# https://github.com/antlr/antlr3

# Configuration
MAIN_CLASS="org.antlr.Tool"
BASE_FLAGS="-Xmx1536m"
CLASSPATH="/usr/share/java/antlr-3.5-complete.jar:$CLASSPATH"
ANTLR_FLAGS=""
JAVACMD="java"

set -x
exec "$JAVACMD" $BASE_FLAGS -classpath "$CLASSPATH" "$MAIN_CLASS" $ANTLR_FLAGS "$@"
